server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lmq981226
    url: jdbc:mysql://localhost:3306/pethome?serverTimezone=Asia/Shanghai&useSSL=false
mybatis:
  type-aliases-package: top.lmqstudy.org.domain,top.lmqstudy.org.query,
                        top.lmqstudy.order.domain,top.lmqstudy.order.query,
                        top.lmqstudy.user.domain,top.lmqstudy.user.query,
                        top.lmqstudy.basic.domain,top.lmqstudy.basic.query,
                        top.lmqstudy.product.domain,top.lmqstudy.product.query,
                        top.lmqstudy.pet.domain,top.lmqstudy.pet.query,
                        top.lmqstudy.pay.domain,top.lmqstudy.pay.query,
logging:
  level:
    top:
      lmqstudy: trace
